### ISSUE TITLE
Media stream player CRA React fail

### ISSUE THREAD

**Issue by cmpeguerog** [AxisCommunications/media-stream-library-js#726] opened 2023-01-25 16:49 UTC
**Describe the bug**
Unable to use stream-media-player on a clean CRA with installed peer dependencies. When **yarn start** command is invoked this error is prompted: **Can't resolve 'media-stream-library' in 'xxx\node_modules\media-stream-player\dist'**

**Environment (please complete the following information):**
 - OS:Windows
 - Browser: Chrome

**Comment by steabert** [comment] 2023-03-18 07:38
Thanks for your report. Do you have a minimal example how to reproduce this?

**Comment by steabert** [comment] 2023-03-18 14:35
Also: note that media-stream-library is a peer dependency of media-stream-player, so you'll need to install it explicitly.

**Comment by ErikMN** [comment] 2023-03-20 20:19
I had the same problem, I worked around it by using react-app-rewired described here: https://github.com/AxisCommunications/media-stream-library-js/issues/743

**Comment by steabert** [comment] 2023-03-23 07:10
Duplicate of #743

**Closed by steabert** 2023-03-23 07:10 UTC
Labels: bug, info needed, player
